Traceback (most recent call last):
  File "/home/bcheng/workspace/dev/cvxpy/ex4/scratch1.py", line 41, in <module>
    time_append = timeit.timeit(lambda: add_rows_append(df_append, new_rows), number=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcheng/workspace/tools/anaconda3/envs/cvxpy/lib/python3.12/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcheng/workspace/tools/anaconda3/envs/cvxpy/lib/python3.12/timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 6, in inner
  File "/home/bcheng/workspace/dev/cvxpy/ex4/scratch1.py", line 41, in <lambda>
    time_append = timeit.timeit(lambda: add_rows_append(df_append, new_rows), number=1)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bcheng/workspace/dev/cvxpy/ex4/scratch1.py", line 25, in add_rows_append
    df = df.append(pd.Series(new_row, index=df.columns), ignore_index=True)
         ^^^^^^^^^
  File "/home/bcheng/workspace/tools/anaconda3/envs/cvxpy/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
